import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {baseline,output,expectedHash} from '../scripts/build.mjs';
const fixture=JSON.parse(await readFile(new URL('./fixtures/ng-v14.1.json',import.meta.url)));
assert.equal(fixture.baselineSha256,expectedHash);
async function load(path){
  const source=await readFile(path,'utf8');
  const boundary='  var MovieViewMode = (function(_super) {';
  assert.equal(source.split(boundary).length,2);
  return vm.runInNewContext(source.slice(0,source.indexOf(boundary))+
    'return {Config,Movie,Movies,Tag,ThumbInfoListener,AdvancedNgRules}; })()',{}, {timeout:1000});
}
const condition=(field,operator,value,not=false)=>({kind:'condition',field,operator,value,not});
const group=(op,children,not=false)=>({kind:'group',op,children,not});
for(const [label,path] of [['baseline',baseline],['generated',output]]){
  test(`${label}: detail application order, shared models and duplicate IDs`,async()=>{
    const {Config,Movie,Movies,ThumbInfoListener}=await load(path);
    const config=new Config((k,d)=>d,()=>{});await config.sync();
    const movies=new Movies(config),a=new Movie('a','original'),b=new Movie('b','second'),c=new Movie('c','third');
    movies.setIfAbsent([a,b,c]);const duplicate=new Movie('a','replacement');movies.setIfAbsent([duplicate]);
    assert.equal(movies.get('a'),a);assert.equal(a.title,'original');
    const trace=[];for(const event of ['descriptionChanged','tagsChanged','contributorChanged','thumbInfoDone'])a.on(event,()=>trace.push([event,a.thumbInfoDone]));
    const complete=ThumbInfoListener.forCompleted(movies);
    const payload=(id,lock=false,name='first',type='user')=>({id,title:'API title',description:'detail',tags:[{name:'shared',lock}],contributor:{type,id:42,name}});
    complete(payload('a'));complete(payload('b',false,'later'));complete(payload('c',true,'channel','channel'));
    assert.deepEqual(trace,[['descriptionChanged',false],['tagsChanged',false],['contributorChanged',false],['thumbInfoDone',true]]);
    assert.equal(a.title,'original');assert.equal(a.description,'detail');
    assert.equal(a.tags[0],b.tags[0]);assert.notEqual(a.tags[0],c.tags[0]);
    if(label==='baseline'){assert.equal(a.contributor,b.contributor);assert.equal(b.contributor.name,'first');}else{assert.notEqual(a.contributor,b.contributor);assert.equal(b.contributor.name,'later');}assert.notEqual(a.contributor,c.contributor);
    config.ngLockedTags.add('shared');assert.deepEqual([a.ng,b.ng,c.ng],[false,false,true]);
    config.ngTags.add('shared');assert.deepEqual([a.ng,b.ng,c.ng],[true,true,true]);
    config.ngTags.clear();config.ngLockedTags.clear();assert.deepEqual([a.ng,b.ng,c.ng],[false,false,false]);
    config.ngChannelIds.add(42);assert.deepEqual([a.ng,b.ng,c.ng],[false,false,true]);
  });
  test(`${label}: failed details notify before done and unknown IDs throw`,async()=>{
    const {Config,Movie,Movies,ThumbInfoListener}=await load(path);
    const config=new Config((k,d)=>d,()=>{});await config.sync();
    const movies=new Movies(config),m=new Movie('failure','title');movies.setIfAbsent([m]);
    const trace=[];m.on('errorChanged',()=>trace.push(['error',m.thumbInfoDone]));m.on('thumbInfoDone',()=>trace.push(['done',m.thumbInfoDone]));
    const fail=ThumbInfoListener.forErrorOccurred(movies);
    fail({id:m.id,error:{type:'ERROR',message:'fixture'}});
    assert.deepEqual(trace,[['error',false],['done',true]]);assert.equal(m.error.type,'ERROR');
    assert.throws(()=>fail({id:'absent',error:{type:'ERROR'}}));
    assert.throws(()=>ThumbInfoListener.forCompleted(movies)({id:'absent'}));
  });
  test(`${label}: tags, configuration changes and notification ordering`,async()=>{
    const {Config,Movie,Movies,ThumbInfoListener}=await load(path);
    const config=new Config((k,d)=>d,()=>{});await config.sync();
    const movies=new Movies(config),m=new Movie('smTags','ordinary');movies.setIfAbsent([m]);
    ThumbInfoListener.forCompleted(movies)({id:m.id,description:'',tags:[{name:'Alpha',lock:false},{name:'Beta',lock:true}],contributor:{type:'user',id:1,name:'x'}});
    const trace=[];m.on('ngChanged',v=>trace.push(v));
    config.ngLockedTags.add('alpha');assert.equal(m.ng,false);
    config.ngTags.add('alpha');assert.equal(m.ng,true);
    config.ngTags.remove(['alpha']);assert.equal(m.ng,false);
    config.ngLockedTags.add('beta');assert.equal(m.ng,true);
    config.ngLockedTags.remove(['beta']);assert.equal(m.ng,false);
    assert.deepEqual(trace,[true,false,true,false]);
    const order=[];m.on('ngTitleChanged',()=>order.push('title'));m.on('ngChanged',()=>order.push('ng'));
    config.ngTitles.add('ordinary');config.ngTitles.remove(['ordinary']);
    assert.deepEqual(order,['title','ng','title','ng']);
  });
  test(`${label}: advertisement readiness and rule updates preserve event order`,async()=>{
    const {Movie,AdvancedNgRules}=await load(path);const m=new Movie('smAd','ad');m.setThumbInfoDone();if(label==='generated')m.setOwnerKnowledge({type:'user',id:12,name:'synthetic',visibility:null});
    const expr=condition('selfAdIdMatch','isTrue','');
    m.updateAdvancedRulesConfig(true,JSON.stringify([{id:'ad',expression:expr}]));
    const state=()=>[AdvancedNgRules.evaluateNode(m,expr),AdvancedNgRules.evaluateNode(m,condition('selfAdIdMatch','isFalse',''))];
    assert.deepEqual(state(),[false,false]);
    const trace=[];m.on('nicoadSelfAdChanged',()=>trace.push(['ad',m.ng]));m.on('ngChanged',v=>trace.push(['ng',v]));
    m.setNicoadSelfAdResult({checked:true,idMatch:true,nameMatch:false});
    assert.deepEqual(state(),[true,false]);assert.equal(m.ng,true);
    m.setNicoadSelfAdResult({checked:false,error:'fixture failure'});
    assert.deepEqual(state(),[false,false]);assert.equal(m.ng,false);
    assert.deepEqual(trace,[['ad',false],['ng',true],['ad',true],['ng',false]]);
    m.setNicoadSelfAdResult({checked:true,idMatch:false,nameMatch:true});
    assert.equal(AdvancedNgRules.evaluateNode(m,condition('selfAdNameMatch','isTrue','')),true);
    m.updateAdvancedRulesConfig(true,JSON.stringify([{id:'name',expression:condition('selfAdNameMatch','isTrue','')}]));
    assert.equal(m.ng,true);m.updateAdvancedRulesConfig(false,'[]');assert.equal(m.ng,false);
  });
  test(`${label}: comparison boundaries, exact tags and missing numeric IDs`,async()=>{
    const {Movie,Tag,AdvancedNgRules}=await load(path);const m=new Movie('smCompare','China report');
    m.tags=[new Tag({name:'Alpha',lock:true}),new Tag({name:'Beta',lock:false})];m.setThumbInfoDone();
    const evaluate=(f,o,v)=>AdvancedNgRules.evaluateNode(m,condition(f,o,v));
    assert.deepEqual(['gt','gte','lt','lte','eq','neq'].map(o=>evaluate('tagCount',o,2)),[false,true,false,true,true,false]);
    assert.deepEqual([evaluate('tag','contains','alpha'),evaluate('tag','contains','alp'),evaluate('lockedTag','contains','beta')],[true,false,false]);
    assert.deepEqual([evaluate('title','contains','CHINA'),evaluate('title','eq','China'),evaluate('title','notContains','Japan')],[true,false,true]);
    assert.deepEqual([evaluate('userId','exists',''),evaluate('userId','notExists',''),evaluate('userId','eq',0)],[false,label==='baseline',label==='baseline']);
    assert.equal(AdvancedNgRules.evaluateNode(m,group('AND',[],true)),false);
    assert.equal(AdvancedNgRules.match(m,true,'{broken',false).length,0);
  });
  test(`${label}: NG fixture states and shared contributor propagation`,async()=>{
    const {Config,Movie,Movies,ThumbInfoListener,AdvancedNgRules}=await load(path);
    const config=new Config((k,d)=>d,()=>{});
    await config.sync();
    const movies=new Movies(config);
    const complete=ThumbInfoListener.forCompleted(movies);
    const make=(id,title='普通の動画',count=0,contributor={type:'user',id:42,name:'author'})=>{
      const m=new Movie(id,title);movies.setIfAbsent([m]);
      complete({id,description:'',tags:Array.from({length:count},(_,i)=>({name:`tag${i}`,lock:true})),contributor});
      return m;
    };
    config.ngLockedTagCountThreshold.value=11;config.ngLockedTagCountEnabled.value=true;
    const ten=make('sm10','普通',10),eleven=make('sm11','普通',11);
    assert.deepEqual([ten.ng,eleven.ng],fixture.lock10and11);
    config.ngTitles.add('中国');
    const title=make('smTitle','中国について');
    assert.equal(title.ng,fixture.titleChina);
    const hundred=Array.from({length:100},(_,i)=>make(`smUser${i}`));
    assert.ok(hundred.every(m=>m.contributor===hundred[0].contributor));
    assert.equal(hundred.filter(m=>m.ng).length,fixture.userCounts[0]);
    config.ngUserIds.add('42');
    assert.equal(hundred.filter(m=>m.ng).length,fixture.userCounts[1]);
    config.ngUserIds.remove([42]);
    assert.equal(hundred.filter(m=>m.ng).length,fixture.userCounts[2]);
    const missing=make('smMissing','普通',0,{type:'unknown',id:-1,name:''});
    assert.equal(missing.ng,fixture.missingSimple);
    const pending=new Movie('smPending','中国について');movies.setIfAbsent([pending]);
    const absent=condition('userId','notExists','');
    const negated=condition('userId','exists','',true);
    const evaluate=(m,node)=>AdvancedNgRules.evaluateNode(m,node,[]);
    assert.deepEqual([evaluate(pending,absent),evaluate(missing,absent),evaluate(pending,negated)],label==='baseline'?fixture.missingStates:[false,false,false]);
    const failed=new Movie('smFailed','普通');movies.setIfAbsent([failed]);
    ThumbInfoListener.forErrorOccurred(movies)({id:failed.id,error:{type:'TEST_ERROR',message:'fixture'}});
    assert.deepEqual([failed.thumbInfoDone,evaluate(failed,absent)],label==='baseline'?fixture.failedStates:[true,false]);
    const a=condition('title','contains','中国'),b=condition('lockedTagCount','gte',11);
    const nodes=[group('AND',[a,b]),group('OR',[a,b]),group('AND',[a,group('OR',[b,condition('title','eq','中国について')])]),group('OR',[a,b],true)];
    assert.deepEqual(nodes.map(n=>evaluate(title,n)),fixture.logic);
    const rules=[{id:'locked',name:'locked',enabled:true,expression:b}];
    config.advancedNgRulesJson.value=JSON.stringify(rules);config.advancedNgRulesEnabled.value=true;
    assert.deepEqual(Array.from(eleven.advancedRuleMatches,m=>m.id),fixture.ruleMatches);
    assert.equal(AdvancedNgRules.match(eleven,false,JSON.stringify(rules),true).length,0);
  });
}
