import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const context = vm.createContext({URL, Map, Set, Date});
vm.runInContext(await readFile(new URL('../src/ui/pager-journey.js', import.meta.url),'utf8'),context);
const pager = context.PagerJourney;
const normalize = x => JSON.parse(JSON.stringify(x));
test('compact ranges skip whole consumed blocks, keeping visit anchors and both boundaries', () => {
  const used=[4,5,6,7,8];
  let m=normalize(pager.layout(3,used,20,2));
  assert.deepEqual(m,{prev:2,next:9,tokens:[{start:1,end:1,current:false},{start:2,end:2,current:false},{start:3,end:3,current:true},{start:4,end:8,consumed:true},{start:9,end:9,current:false},{start:10,end:10,current:false}]});
  m=normalize(pager.layout(9,[...used,10,11,12,13],20,2));
  assert.equal(m.prev,3); assert.equal(m.next,14);
  assert.deepEqual(m.tokens.filter(x=>x.consumed),[{start:4,end:8,consumed:true},{start:10,end:13,consumed:true}]);
  assert.equal(pager.layout(1,[],1).prev,null); assert.equal(pager.layout(1,[],1).next,null);
  assert.equal(pager.layout(3,used,8).next,null);
  assert.equal(pager.layout(3,[4,5],20).next,6,'partially read page remains next');
});
test('history survives same-query SPA pages, resets for criteria, NG changes, expiry', () => {
  const url='https://www.nicovideo.jp/tag/test?sort=hot&page=3';
  const a=pager.history(url,'ng-A',100); a.pages.set(4,true);
  assert.equal(pager.history(url.replace('page=3','page=9')+'&rf=card','ng-A',200),a);
  assert.equal(pager.history(url.replace('sort=hot','sort=new'),'ng-A',200).pages.size,0);
  assert.equal(pager.history(url,'ng-B',200).pages.size,0);
  pager.history(url,'ng-B',200).pages.set(5,true);
  assert.equal(pager.history(url,'ng-B',200+31*60*1000).pages.size,0);
});
test('a previously visited page becomes consumed only after all its fetched videos settle', () => {
  const config={autoFillPagerMode:{value:'off'},pagerPreviewCount:{value:2},ngTitles:{set:new Set()}};
  const page={doc:{},_disposed:false},href='https://www.nicovideo.jp/tag/revisit';
  const earlier=pager.create(page,config,href+'?page=3');
  earlier.update(30,()=>true);
  const current=pager.create(page,config,href+'?page=1');
  assert.deepEqual(normalize(current.update(30,()=>true)),[],'visiting page 3 alone does not consume it');
  for(let n=2;n<=4;n++)current.record(n,[{id:'synthetic-'+n}]);
  current.record(3,[{id:'synthetic-3'},{id:'unshown'}]);
  assert.deepEqual(normalize(current.update(30,id=>id!=='unshown')),[2,4],'partially processed page remains accessible');
  assert.deepEqual(normalize(current.update(30,()=>true)).sort((a,b)=>a-b),[2,3,4],'completed page 3 joins the consumed range');
  assert.equal(pager.layout(1,current.update(30,()=>true),30).next,5);
  assert.deepEqual(normalize(current.update(30,id=>id!=='unshown')).sort((a,b)=>a-b),[2,4],'newly unsettled page becomes accessible again');
  current.record(1,[{id:'current'}]);
  assert.ok(!current.update(30,()=>true).includes(1),'current page remains the selected anchor');
  config.ngTitles.set.add('changed');
  assert.deepEqual(normalize(current.update(30,()=>false)),[],'changed rules invalidate previous consumption');
});
